map:
  min_lat: -40
  max_lat: -20
  min_long: -20
  max_long: 0

file:
  package_name: mpc_amiga
  barn_field: gps_coordinates/barn_field_waypoints.txt
  stopping: gps_coordinates/stopping_points.txt
  pruning: gps_coordinates/pruning_points_real.txt